---
- name: create system group
  group:
    name: "{{ vmware_exporter_system_group }}"
    system: true
    state: present
  when: vmware_exporter_system_group != "root"
  become: true
  tags: vmware_exporter

- name: create system user
  user:
    name: "{{ vmware_exporter_system_user }}"
    system: true
    shell: "/sbin/nologin"
    group: "{{ vmware_exporter_system_group }}"
    createhome: false
  when: vmware_exporter_system_user != "root"
  become: true
  tags: vmware_exporter

- name: create data directory
  file:
    path: "{{ vmware_exporter_config_dir }}"
    state: directory
    owner: "{{ vmware_exporter_system_user }}"
    group: "{{ vmware_exporter_system_group }}"
    mode: 0755
  become: true
  tags: vmware_exporter

- name: ensure python3, pyOpenSSL and pip3 are installed
  package:
    name:
      - python-setuptools
      - python36
      - python36-devel
      - python36-pip
      - python36-pyOpenSSL
    state: present
    update_cache: yes
  environment: "{{proxy_env}}"
  become: true
  tags: vmware_exporter

- name: ensure vmware_exporter is installed (via pip3)
  pip:
    name: vmware_exporter
    executable: /bin/pip3
    state: present
  environment: "{{proxy_env}}"
  become: true
  tags: vmware_exporter

- name: configure vmware_exporter
  template:
    src: config.yml.j2
    dest: "{{ vmware_exporter_config_dir }}/config.yml"
    owner: "{{ vmware_exporter_system_user }}"
    group: "{{ vmware_exporter_system_group }}"
    mode: 0644
  notify: restart vmware_exporter
  become: true
  tags: vmware_exporter

- name: copy systemd service unit
  template:
    src: vmware_exporter.service.j2
    dest: /etc/systemd/system/vmware_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart vmware_exporter
  become: true
  tags: vmware_exporter

- name: ensure service is started and enabled
  systemd:
    daemon_reload: true
    name: vmware_exporter
    state: started
    enabled: true
  become: true
  tags: vmware_exporter
