---
- name: restart vmware_exporter
  systemd:
    daemon_reload: true
    name: vmware_exporter
    state: restarted
  become: true
  tags: vmware_exporter

- name: reload ufw
  systemd:
    name: ufw
    state: reloaded
  tags: vmware_exporter
  become: true

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded
  tags: vmware_exporter
  become: true